import 'package:flutter/material.dart';
class AppTheme {
  static Color colorX = Color(0xff99ff05);
  static List<Color> colorOptions = [
    Colors.purple,
    Colors.green,
    Colors.teal,
    Colors.yellow,
    Colors.orange,
    Colors.pink,
    colorX
  ];
  AppTheme._();
  static List<String> colorText = <String>[
  "blue",
  "red",
  "green",
  "purple",
  ];

  static List<String> colorTextLD= <String>["blue", "red", "green", "purple"];
  static List<Color> colorOptionsLD=<Color>[Colors.blue, Colors.red, Colors.green, Colors.deepPurple];

  static List<ColorScheme> colorOptionsShemeL = [
    lightColorSchemeblue,
    lightColorSchemered,
    lightColorSchemegreen,
    lightColorSchemepurple

  ];
  static List<ColorScheme> colorOptionsShemeD = [
    darkColorSchemeblue,
    darkColorSchemered,
    darkColorSchemegreen,
    darkColorSchemepurple
  ];
  static ThemeData themeDataLight=ThemeData(useMaterial3: useMaterial3,
      colorScheme: AppTheme.colorOptionsShemeL[AppTheme.colorSelected]);
  static ThemeData themeDataDark=ThemeData(useMaterial3: useMaterial3,
      colorScheme: AppTheme.colorOptionsShemeD[AppTheme.colorSelected]);

  static bool useMaterial3 = false;
  static bool useLightMode = true;
  static int colorSelected = 1;
  static ThemeData themeData = ThemeData(
    //modo noche o modo dia
      colorSchemeSeed: AppTheme.colorOptions[AppTheme.colorSelected],
      useMaterial3: AppTheme.useMaterial3,
      brightness: AppTheme.useLightMode ? Brightness.light : Brightness.dark);



  static const lightColorSchemeblue = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF006496),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFCBE6FF),
    onPrimaryContainer: Color(0xFF001E31),
    secondary: Color(0xFF50606F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD4E4F6),
    onSecondaryContainer: Color(0xFF0D1D2A),
    tertiary: Color(0xFF66587B),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFECDCFF),
    onTertiaryContainer: Color(0xFF211534),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFCFCFF),
    onBackground: Color(0xFF1A1C1E),
    surface: Color(0xFFFCFCFF),
    onSurface: Color(0xFF1A1C1E),
    surfaceVariant: Color(0xFFDEE3EA),
    onSurfaceVariant: Color(0xFF42474D),
    outline: Color(0xFF72787E),
    onInverseSurface: Color(0xFFF0F0F4),
    inverseSurface: Color(0xFF2F3133),
    inversePrimary: Color(0xFF90CDFF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF006496),
    outlineVariant: Color(0xFFC1C7CE),
    scrim: Color(0xFF000000),
  );

  static const darkColorSchemeblue = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF90CDFF),
    onPrimary: Color(0xFF003350),
    primaryContainer: Color(0xFF004B72),
    onPrimaryContainer: Color(0xFFCBE6FF),
    secondary: Color(0xFFB8C8D9),
    onSecondary: Color(0xFF22323F),
    secondaryContainer: Color(0xFF394856),
    onSecondaryContainer: Color(0xFFD4E4F6),
    tertiary: Color(0xFFD1BFE7),
    onTertiary: Color(0xFF372B4A),
    tertiaryContainer: Color(0xFF4E4162),
    onTertiaryContainer: Color(0xFFECDCFF),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1A1C1E),
    onBackground: Color(0xFFE2E2E5),
    surface: Color(0xFF1A1C1E),
    onSurface: Color(0xFFE2E2E5),
    surfaceVariant: Color(0xFF42474D),
    onSurfaceVariant: Color(0xFFC1C7CE),
    outline: Color(0xFF8C9198),
    onInverseSurface: Color(0xFF1A1C1E),
    inverseSurface: Color(0xFFE2E2E5),
    inversePrimary: Color(0xFF006496),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF90CDFF),
    outlineVariant: Color(0xFF42474D),
    scrim: Color(0xFF000000),
  );

  static const lightColorSchemered = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFB72200),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFDAD3),
    onPrimaryContainer: Color(0xFF3E0500),
    secondary: Color(0xFF77574F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFDAD3),
    onSecondaryContainer: Color(0xFF2C1510),
    tertiary: Color(0xFF8E437E),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD7F0),
    onTertiaryContainer: Color(0xFF3A0033),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF201A19),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF201A19),
    surfaceVariant: Color(0xFFF5DDD9),
    onSurfaceVariant: Color(0xFF534340),
    outline: Color(0xFF85736F),
    onInverseSurface: Color(0xFFFBEEEB),
    inverseSurface: Color(0xFF362F2D),
    inversePrimary: Color(0xFFFFB4A4),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFB72200),
    outlineVariant: Color(0xFFD8C2BD),
    scrim: Color(0xFF000000),
  );

  static const darkColorSchemered = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFB4A4),
    onPrimary: Color(0xFF640E00),
    primaryContainer: Color(0xFF8C1800),
    onPrimaryContainer: Color(0xFFFFDAD3),
    secondary: Color(0xFFE7BDB4),
    onSecondary: Color(0xFF442A24),
    secondaryContainer: Color(0xFF5D3F39),
    onSecondaryContainer: Color(0xFFFFDAD3),
    tertiary: Color(0xFFFFACE8),
    onTertiary: Color(0xFF57124D),
    tertiaryContainer: Color(0xFF722B65),
    onTertiaryContainer: Color(0xFFFFD7F0),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF201A19),
    onBackground: Color(0xFFEDE0DD),
    surface: Color(0xFF201A19),
    onSurface: Color(0xFFEDE0DD),
    surfaceVariant: Color(0xFF534340),
    onSurfaceVariant: Color(0xFFD8C2BD),
    outline: Color(0xFFA08C88),
    onInverseSurface: Color(0xFF201A19),
    inverseSurface: Color(0xFFEDE0DD),
    inversePrimary: Color(0xFFB72200),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFFFB4A4),
    outlineVariant: Color(0xFF534340),
    scrim: Color(0xFF000000),
  );
  static const lightColorSchemegreen = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF396A00),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFB3F576),
    onPrimaryContainer: Color(0xFF0D2000),
    secondary: Color(0xFF57624A),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDAE7C9),
    onSecondaryContainer: Color(0xFF151E0C),
    tertiary: Color(0xFF386664),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFBBECE9),
    onTertiaryContainer: Color(0xFF00201F),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFDFCF5),
    onBackground: Color(0xFF1B1C18),
    surface: Color(0xFFFDFCF5),
    onSurface: Color(0xFF1B1C18),
    surfaceVariant: Color(0xFFE0E4D6),
    onSurfaceVariant: Color(0xFF44483E),
    outline: Color(0xFF74796D),
    onInverseSurface: Color(0xFFF2F1EA),
    inverseSurface: Color(0xFF2F312C),
    inversePrimary: Color(0xFF99D85E),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF396A00),
    outlineVariant: Color(0xFFC4C8BA),
    scrim: Color(0xFF000000),
  );

  static const darkColorSchemegreen = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF99D85E),
    onPrimary: Color(0xFF1B3700),
    primaryContainer: Color(0xFF2A5000),
    onPrimaryContainer: Color(0xFFB3F576),
    secondary: Color(0xFFBECBAE),
    onSecondary: Color(0xFF29341F),
    secondaryContainer: Color(0xFF3F4A34),
    onSecondaryContainer: Color(0xFFDAE7C9),
    tertiary: Color(0xFFA0CFCD),
    onTertiary: Color(0xFF003736),
    tertiaryContainer: Color(0xFF1E4E4C),
    onTertiaryContainer: Color(0xFFBBECE9),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1B1C18),
    onBackground: Color(0xFFE3E3DC),
    surface: Color(0xFF1B1C18),
    onSurface: Color(0xFFE3E3DC),
    surfaceVariant: Color(0xFF44483E),
    onSurfaceVariant: Color(0xFFC4C8BA),
    outline: Color(0xFF8E9286),
    onInverseSurface: Color(0xFF1B1C18),
    inverseSurface: Color(0xFFE3E3DC),
    inversePrimary: Color(0xFF396A00),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF99D85E),
    outlineVariant: Color(0xFF44483E),
    scrim: Color(0xFF000000),
  );
  static const lightColorSchemepurple = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFAB178E),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFD8ED),
    onPrimaryContainer: Color(0xFF3B002F),
    secondary: Color(0xFF705766),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFADAEB),
    onSecondaryContainer: Color(0xFF281622),
    tertiary: Color(0xFF81533F),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFDBCC),
    onTertiaryContainer: Color(0xFF321304),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1F1A1D),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1F1A1D),
    surfaceVariant: Color(0xFFEFDEE6),
    onSurfaceVariant: Color(0xFF4F444A),
    outline: Color(0xFF81737A),
    onInverseSurface: Color(0xFFF9EEF1),
    inverseSurface: Color(0xFF342F31),
    inversePrimary: Color(0xFFFFADE2),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFAB178E),
    outlineVariant: Color(0xFFD3C2CA),
    scrim: Color(0xFF000000),
  );

  static const darkColorSchemepurple = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFADE2),
    onPrimary: Color(0xFF5F004E),
    primaryContainer: Color(0xFF86006F),
    onPrimaryContainer: Color(0xFFFFD8ED),
    secondary: Color(0xFFDDBECF),
    onSecondary: Color(0xFF3F2A37),
    secondaryContainer: Color(0xFF57404E),
    onSecondaryContainer: Color(0xFFFADAEB),
    tertiary: Color(0xFFF4B9A0),
    onTertiary: Color(0xFF4B2715),
    tertiaryContainer: Color(0xFF653C29),
    onTertiaryContainer: Color(0xFFFFDBCC),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1F1A1D),
    onBackground: Color(0xFFEAE0E3),
    surface: Color(0xFF1F1A1D),
    onSurface: Color(0xFFEAE0E3),
    surfaceVariant: Color(0xFF4F444A),
    onSurfaceVariant: Color(0xFFD3C2CA),
    outline: Color(0xFF9B8D94),
    onInverseSurface: Color(0xFF1F1A1D),
    inverseSurface: Color(0xFFEAE0E3),
    inversePrimary: Color(0xFFAB178E),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFFFADE2),
    outlineVariant: Color(0xFF4F444A),
    scrim: Color(0xFF000000),
  );



}//Comentar